---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /opt/homebrew-cask/Caskroom/firefox/latest/Firefox.app
    - /opt/homebrew-cask/Caskroom/iterm2/1.0.0/iTerm.app
    folders:
    - path: ~/
    - path: ~/Downloads
      sort: datemodified
  #- role: cask_package
    #package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  #- role: cask_package
  #  tap: caskroom/fonts
  #  package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: ericj
    git_user_email: eric.junker@dice.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  - role: brew_package
    package_name: the_silver_searcher
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  - role: cask_package
    package_name: iterm2
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: hipchat
  - role: cask_package
    package_name: sourcetree
  - role: cask_package
    package_name: sequel-pro
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: dash
  - role: cask_package
    package_name: alfred
  - role: cask_package
    package_name: textwrangler
  #- role: cask_package
  #  package_name: spectacle
  - role: cask_package
    package_name: sizeup
  - role: cask_package
    package_name: virtualbox

